<div class="container">
    <div class="box-error">
        <h1>Page Not Found <span>Error 404</span></h1>
        <p class="text-error mt-5 mb-3">
            The page you requested could not be found. Use your browser <strong>Back</strong> button to navigate to the page 
            you have prevously come from.
        </p>
        <p class="text-error text-center mb-5">
            Or you could just press this neat little button.
        </p>
        <a href="/" class="btn btn-lg btn-primary"><i class="fas fa-home"></i>Take Me Home</a>
    </div>
</div>

